# -*- coding: utf-8 -*-
"""2502110001(LAB-05).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Z6WFLXOJd8mO8hnLXL97_EVszWfsXNX
"""

# IT12: Rough Cut - Parsing one log line
line = "  PE-26-0137 ; 25.02 ; DAY  "

# Extract fields
fields = line.strip().split(";")
code = fields[0].strip()
dia = float(fields[1])
shift = fields[2].strip().upper()

# Output results
print("Part Code:", code)
print("Diameter:", dia)
print("Shift:", shift)

# Proof that dia is a float
print("Proof (dia + 0.01):", dia + 0.01)

# IT10: Standard - Processing 10 log lines
log_lines = [
    "  PE-26-0137 ; 25.02 ; DAY  ",
    " PE-26-0138 ; 24.98 ; DAY ",
    "PE-26-0139 ; 25.05 ; NIGHT",
    "  PE-26-0140 ; 24.92 ; DAY ",
    "PE-26-0141 ; 25.10 ; NIGHT ",
    " PE-26-0142 ; 25.00 ; DAY  ",
    "PE-26-0143 ; 24.95 ; DAY",
    "  PE-26-0144 ; 25.08 ; NIGHT ",
    "PE-26-0145 ; 24.90 ; DAY  ",
    " PE-26-0146 ; 25.03 ; NIGHT "
]

diameters = []

for line in log_lines:
    fields = line.strip().split(";")
    dia = float(fields[1])
    diameters.append(dia)


count = len(diameters)
avg_dia = sum(diameters) / count
min_dia = min(diameters)
max_dia = max(diameters)


print("=== IT10 SHIFT LOG REPORT ===")
print("Total Items Processed:", count)
print("Average Diameter:", round(avg_dia, 3))
print("Minimum Diameter:", min_dia)
print("Maximum Diameter:", max_dia)

# IT8: Fine - Binned Filtering & Shift Report
log_lines = [
    "  PE-26-0137 ; 25.02 ; DAY  ",
    " PE-26-0138 ; 24.98 ; DAY ",
    "PE-26-0139 ; 25.05 ; NIGHT",
    "  PE-26-0140 ; 24.92 ; DAY ",
    "PE-26-0141 ; 25.10 ; NIGHT ",
    " PE-26-0142 ; 25.00 ; DAY  ",
    "PE-26-0143 ; 24.95 ; DAY",
    "  PE-26-0144 ; 25.08 ; NIGHT ",
    "PE-26-0145 ; 24.90 ; DAY  ",
    " PE-26-0146 ; 25.03 ; NIGHT "
]

accepted = []
rework = []
scrap = []

scrapped_part_codes = []


for line in log_lines:
    fields = line.strip().split(";")
    code = fields[0].strip()
    dia = float(fields[1])

    if 24.98 <= dia <= 25.02:
        accepted.append(dia)
    elif (24.95 <= dia < 24.98) or (25.02 < dia <= 25.05):
        rework.append(dia)
    else:
        scrap.append(dia)
        scrapped_part_codes.append(code)

avg_accepted = sum(accepted) / len(accepted) if accepted else 0.0


print("=== IT8 QUALITY INSPECTION REPORT ===")
print("Accepted Count:", len(accepted))
print("Rework Count  :", len(rework))
print("Scrap Count   :", len(scrap))
print("Average Accepted Diameter:", round(avg_accepted, 3))
print("Scrapped Part Codes      :", scrapped_part_codes)

# IT6: Precision - Shift Comparison using Sets
log_lines = [
    "  PE-26-0137 ; 25.02 ; DAY  ",
    " PE-26-0138 ; 24.98 ; DAY ",
    "PE-26-0139 ; 25.05 ; NIGHT",
    "  PE-26-0140 ; 24.92 ; DAY ",
    "PE-26-0141 ; 25.10 ; NIGHT ",
    " PE-26-0142 ; 25.00 ; DAY  ",
    "PE-26-0143 ; 24.95 ; DAY",
    "  PE-26-0144 ; 25.08 ; NIGHT ",
    "PE-26-0145 ; 24.90 ; DAY  ",
    " PE-26-0146 ; 25.03 ; NIGHT "
]

# Trackers for Day and Night shifts
day_total = 0
day_accepted = 0
night_total = 0
night_accepted = 0

# Sets to store unique scrapped part codes per shift
# Comment: Sets are used here because they enforce uniqueness and enable set operations (intersection/difference).
day_scrap_codes = set()
night_scrap_codes = set()

for line in log_lines:
    fields = line.strip().split(";")
    code = fields[0].strip()
    dia = float(fields[1])
    shift = fields[2].strip().upper()

    is_accepted = (24.98 <= dia <= 25.02)
    is_rework = (24.95 <= dia < 24.98) or (25.02 < dia <= 25.05)
    is_scrap = not (is_accepted or is_rework)

    if shift == "DAY":
        day_total += 1
        if is_accepted:
            day_accepted += 1
        elif is_scrap:
            day_scrap_codes.add(code)
    elif shift == "NIGHT":
        night_total += 1
        if is_accepted:
            night_accepted += 1
        elif is_scrap:
            night_scrap_codes.add(code)

# Calculate acceptance rates
day_acc_rate = (day_accepted / day_total * 100) if day_total else 0.0
night_acc_rate = (night_accepted / night_total * 100) if night_total else 0.0

# Set operations
scrapped_in_both = day_scrap_codes.intersection(night_scrap_codes)
day_only_scrap = day_scrap_codes.difference(night_scrap_codes)
night_only_scrap = night_scrap_codes.difference(day_scrap_codes)

# Output Report
print("=== IT6 SHIFT COMPARISON REPORT ===")
print(f"Day Shift Acceptance Rate  : {day_acc_rate:.1f}% ({day_accepted}/{day_total})")
print(f"Night Shift Acceptance Rate: {night_acc_rate:.1f}% ({night_accepted}/{night_total})")
print("Scrapped in BOTH shifts     :", scrapped_in_both)
print("Scrapped ONLY in Day shift  :", day_only_scrap)
print("Scrapped ONLY in Night shift:", night_only_scrap)