# -*- coding: utf-8 -*-
"""2502110001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcRrS8KP52dOKOj-Lgo6Rh07f36NEaM7
"""

print("cloud ok")

name=input("Operator name:")
print("Hello,",name)

accept_count = 0
rework_count = 0
scrap_count = 0

for i in range(10):
    diameter = float(input(f"Enter diameter for part {i+1}: "))

    if 24.95 <= diameter <= 25.05:
        print("ACCEPT")
        accept_count += 1
    elif 24.80 <= diameter < 24.95:
        print("REWORK")
        rework_count += 1
    else:
        print("SCRAP")
        scrap_count += 1

print("\n--- Final Batch Report ---")
print(f"ACCEPT: {accept_count} | REWORK: {rework_count} | SCRAP: {scrap_count}")

