# -*- coding: utf-8 -*-
"""2502110001(lab-04).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SjbnFMIHNUugl3gBGiqHbkO5d5pG8mC4
"""

import random

print("--- IT12: Ten From the Machine ---")

for i in range(10):
    diameter = random.uniform(24.90, 25.10)
    diameter = round(diameter, 2)
    print(f"Part {i + 1}: {diameter} mm")

import random


accept_count = 0
rework_count = 0
scrap_count = 0

print("--- IT10: The Self-Sorting Bench ---")


for i in range(10):
    diameter = random.uniform(24.90, 25.10)
    diameter = round(diameter, 2)

    # Binning logic
    if 24.95 <= diameter <= 25.05:
        status = "ACCEPT"
        accept_count += 1
    elif 24.90 <= diameter < 24.95:
        status = "REWORK"
        rework_count += 1
    else:
        status = "SCRAP"
        scrap_count += 1

    print(f"Part {i + 1}: {diameter} mm -> {status}")

print("\n--- SHIFT REPORT ---")
print(f"Total Accepted : {accept_count}")
print(f"Total Rework   : {rework_count}")
print(f"Total Scrap    : {scrap_count}")

import random
accept_count = 0
rework_count = 0
scrap_count = 0

print("--- IT10: The Self-Sorting Bench ---")
for i in range(100):
    diameter = random.uniform(24.90, 25.10)
    diameter = round(diameter, 2)

    if 24.95 <= diameter <= 25.05:
        status = "ACCEPT"
        accept_count += 1
    elif 24.90 <= diameter < 24.95:
        status = "REWORK"
        rework_count += 1
    else:
        status = "SCRAP"
        scrap_count += 1

    print(f"Part {i + 1}: {diameter} mm -> {status}")

print("\n--- SHIFT REPORT ---")
print(f"Total Accepted : {accept_count}")
print(f"Total Rework   : {rework_count}")
print(f"Total Scrap    : {scrap_count}")

import random

mode = input("Choose mode (1: Halt on Scrap, 2: Skip Scrap): ").strip()

accept_count = 0
rework_count = 0
scrap_count = 0
total_inspected = 0

print("\n--- IT8: Halt/Skip Bench ---")

for i in range(1, 101):
    diameter = round(random.uniform(24.90, 25.10), 2)


    if 24.95 <= diameter <= 25.05:
        status = "ACCEPT"
        accept_count += 1
    elif 24.90 <= diameter < 24.95:
        status = "REWORK"
        rework_count += 1
    else:
        status = "SCRAP"
        scrap_count += 1

        if mode == "1":
            print(f"Part {i}: {diameter} mm -> SCRAP detected! HALTING BATCH.")
            total_inspected = i
            break
        elif mode == "2":

            continue

    total_inspected = i
    print(f"Part {i}: {diameter} mm -> {status}")

print("\n--- SHIFT REPORT ---")
print(f"Total Inspected: {total_inspected}")
print(f"Total Accepted : {accept_count}")
print(f"Total Rework   : {rework_count}")
print(f"Total Scrap    : {scrap_count}")

import random

consecutive_accepts = 0
total_parts = 0
max_safety_cap = 500

print("--- IT6: Run Until 5 Consecutive ACCEPTs ---")

while consecutive_accepts < 5 and total_parts < max_safety_cap:
    total_parts += 1
    diameter = round(random.uniform(24.90, 25.10), 2)

    if 24.95 <= diameter <= 25.05:
        status = "ACCEPT"
        consecutive_accepts += 1
    elif 24.90 <= diameter < 24.95:
        status = "REWORK"
        consecutive_accepts = 0  # Reset counter
    else:
        status = "SCRAP"
        consecutive_accepts = 0  # Reset counter

    print(f"Part {total_parts}: {diameter} mm -> {status} (Streak: {consecutive_accepts})")

print("\n--- SUMMARY ---")
print(f"Total parts machined to get 5 ACCEPTs in a row: {total_parts}")